/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package assessment;

public class App {

    public static void main(String[] args) {
//       PalindromChecker palindromChecker = new PalindromChecker(121);
//        System.out.println(palindromChecker.isPalindrom);

//        RomanToInt romanToInt = new RomanToInt("MCMXCIV");
//        System.out.println(romanToInt.value);

//        String[] StringArray = {"flower","flow","flight"};
//        LongestPrefix longestPrefix = new LongestPrefix(StringArray);
//        System.out.println(longestPrefix.prefixString);

//        MergeString mergeString = new MergeString("abcd", "pq");
//        System.out.println(mergeString.output);

//        ValidParentheses validParentheses = new ValidParentheses("()[}{}");
//        System.out.println(validParentheses.isValid);

        BinaryTree binaryTree = new BinaryTree();
        binaryTree.addNode(10);
        binaryTree.addNode(9);
        binaryTree.addNode(11);
        binaryTree.addNode(8);
        binaryTree.addNode(1);
        binaryTree.printLeftPart();

    }
}
