/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package assessment;

import org.junit.jupiter.api.Test;

import static org.junit.jupiter.api.Assertions.assertNotNull;

class AssessmentTest {
    @Test void appHasAGreeting() {
        App classUnderTest = new App();
    }
}
