/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package assessment;

import org.junit.Test;

class AssessmentTest {
    @Test
    void appHasAGreeting() {
        App classUnderTest = new App();
    }
}
